version: "3"
services:
#----------------------------------------------------BACKEND
  backend:
    #Naming system for image and container
    image: image-backend
    container_name: container-backNGINX

    #Building image locally from Dockerfile
    build:
      context: ./0-backend-NGINX
      dockerfile: Dockerfile

    #Container support
    networks:
      - inception-net
    ports:
      - "443:80"
    
    env_file:
      - .env
    depends_on:
      - frontend #depende del frontend montado en WP por cuestiones de configuración de NGINX
    restart: always #if it stops in an unexpected way, it will restart.
#----------------------------------------------------DATABASE
  database:
    container_name: container-dbMARIA
    image: image-database
    build:
      context: ./1-database-MARIA
      dockerfile: Dockerfile
    
    networks:
      - inception-net
    ports:
     - 3306:3306 #por defecto mariaDB
    
    volumes:
      - volume-database:/container-volume

    env_file:
      - .env

    restart: always
    #--env MARIADB_ROOT_PASSWORD=my-secret-pw
    #_GUILLE admin username must not include 'admin' or 'Admin' (e.g., admin, administrator, Admin-login, admin-123, and so forth)
    command: tail -f /dev/null
#----------------------------------------------------FRONTEND
  frontend:
    container_name: container-frontWP
    image: image-front
    build:
      context: ./2-frontend-WP
      dockerfile: Dockerfile

    networks:
      - inception-net
    #ports:
     # -
    volumes:
      - volume-frontend:/container-volume

    depends_on:
      - database
    restart: always

    
    command: tail -f /dev/null

#----------------------------------------------------SUPPORT
networks:
  inception-net:
    name: network-inception
    driver: bridge

volumes:
  volume-database:
  volume-frontend: