version: "3"
services:
#----------------------------------------------------BACKEND
  backend:
    #NAMING SYSTEM------------------------------------------
    image: image-nginx
    container_name: container-nginx
    #BUILD from Dockerfile----------------------------------
    build:
      context: ./0-backend-NGINX
      dockerfile: Dockerfile
    #NETWORK AND EXPOSED PORTS-------------------------------
    networks:
      - inception-net
    ports:
      - "443:443"
    #VOLUMES AND SUPPORT-------------------------------------
    volumes:
      - volume-frontend:/var/www/html
    env_file:
      - .env
    depends_on:
      - frontend #requires WP (explained in NGINX configuration)
    restart: always #restart it unexpected stop
#----------------------------------------------------DATABASE
  database:
    #NAMING SYSTEM------------------------------------------
    container_name: container-mariadb
    image: image-mariadb
    #BUILD from Dockerfile----------------------------------
    build:
      context: ./1-database-MARIA
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ROOT_PASSWORD2: ${MYSQL_ROOT_PASSWORD2}
        MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
    #NETWORK AND EXPOSED PORTS-------------------------------
    networks:
      - inception-net
    #VOLUMES AND SUPPORT-------------------------------------
    volumes:
      - volume-database:/var/lib/mysql/
    env_file:
      - .env
    restart: always
#----------------------------------------------------FRONTEND
  frontend:
    #NAMING SYSTEM------------------------------------------
    container_name: container-wordpress
    image: image-wordpress
    #BUILD from Dockerfile----------------------------------
    build:
      context: ./2-frontend-WP
      dockerfile: Dockerfile
    #NETWORK AND EXPOSED PORTS-------------------------------
    networks:
      - inception-net
    #VOLUMES AND SUPPORT-------------------------------------
    volumes:
      - volume-frontend:/var/www/html
    depends_on:
      - database # DB must be built first.
    env_file:
      - .env
    restart: always
#----------------------------------------------------SUPPORT
networks:
  inception-net:
    name: inception-network
    driver: bridge

volumes:
  volume-database:
    name: volume-database
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/guilmira/data/volume-database'
  volume-frontend:
    name: volume-frontend
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/guilmira/data/volume-frontend'