services:
  busybox:
    image: busybox
    container_name: whale1
    networks:
      - blueguille
    command: tail -f /dev/null

  custom:
    image: c2
    container_name: whale2
    networks:
      - blueguille
    command: tail -f /dev/null

networks:
  blueguille:
    name: blueguille
    driver: bridge